---
title: "Exercício 03 - 07/07/2017"
output: github_document
---

-   [Exercício 01](#Exercicio_01)
-   [Exercício 02](#Exercicio_02)
-   [Exercício 03](#Exercicio_03)
-   [Exercício 04](#Exercicio_04)



Exercício 01
------------
###The	“hotdog” variable for	the	“Hot	Dogs	in	Baltimore”	example	can	be	better	defined.

#### R.)Existem duas possibilidades, a primeira seria incluir todas as possíveis combinações de maiuscula e minuscula de Hot Dog que existem, e a outra seria utilizar o 'ignore.case = TRUE' 
Caso 1
```{r}
grep("Hot dog|Hot Dog| Hot dogs| Hot Dogs",bVendors$ItemsSold)

```

```{r}
grepl("Hot dog|Hot Dogs",bVendors$ItemsSold,ignore.case = TRUE)

```

Exercício 02
------------
### Create	a	“pizza”	variable	then
####R.)

```{r}

grepl("Pizza",bVendors$ItemsSold,ignore.case = TRUE)


```
Exercício 03
------------
### Get	the	name	of	the	town	for	the	“Hot	Dogs	in	Baltimore”.
#### R.)


```{r}
bVendors$TownZ = do.call(rbind,strsplit(bVendors$location,"\n"))[,1]
bVendors$Town = strtrim(bVendors$Town,nchar(bVendors$Town)-6)
bVendors$TownZ = NULL
bVendors$Town[grep("Hot Dog|Hot Dogs",bVendors$ItemsSold,ignore.case = TRUE)]


```
Exercício 04
------------
###Complete	the	Codebook	for	the	“Hot	Dogs	in	Baltimore”	example.

Passo 1 - Importando os dados de entrada

```{r}
#Armazenando a URL em uma variavel 
site = "https://data.baltimorecity.gov/api/views/bqw3-z52q/rows.csv?accessType=DOWNLOAD"

#Baixa o arquivo e salva na pasta "TempData" com o nome Bfood.csv
#Realiza um teste para ver se já existe um arquivo 
if (file.exists("./TempData/BFood.csv")) 
  {
  tam = file.info("./TempData/BFood.csv")$size # armazena o tamnho do arquivo
  cdata = file.info("./TempData/BFood.csv")$ctime #armazena a data de criação
  paste("Arquivo já existe. ",tam,"bytes. Criado em:",cdata)
  } else
  {
    download.file(site,destfile = "./TempData/BFood.csv",method="curl")
    "Arquivo baixado com sucesso!"
  }

bVendors <- read.csv(file="./TempData/BFood.csv", header=TRUE, sep=",", stringsAsFactors=FALSE)

str(bVendors) # Mostra um pedaço do arquivo importado
```

Passo 2 - Linpando Dados Vazios, desnecessários e Renomeando Colunas
```{r}
#Excluindo os dados de ID e ST
bVendors$Id = NULL
bVendors$St = NULL

#Renomeando a coluna Location1
names(bVendors)[names(bVendors) == "Location.1"] <- "location"

str(bVendors)
```

Passo 3 - Organizando os dados de Localização

```{r}
##Dividindo a coluna de Localização em 4 partes, Town, ZipCode, Lat e Long
# A primeira divisão é quebrar a coluna Location pelo separador '\n' e guardar a primeira parte
bVendors$TownZ = do.call(rbind,strsplit(bVendors$location,"\n"))[,1]

#Retirar da string resultante o nome da Cidade (neste caso foi eliminado os 5 ultimos caracteres referente ao ZIP code)
bVendors$Town = strtrim(bVendors$TownZ,nchar(bVendors$Town)-6)

cat("\nTowns: ", head(bVendors$Town))

# Retirar da primeira parta da string location o ZIPcode (os últimos 5 caracteres)
bVendors$ZIP = substring(bVendors$TownZ,nchar(bVendors$TownZ)-5)

cat("\nZipCode: ", head(bVendors$ZIP))

# Os dados de LAT LONG estão dentro de '()'. Assim foi necessário retirar esses caracteres da segunda parte do string
bVendors$LatLong = do.call(rbind,strsplit(bVendors$location,"\n"))[,2]
bVendors$LatLong = gsub("\\(|)","",bVendors$LatLong)

# Dividiu a coluna de LatLong pelo separador ',' obtendo os resultados de LAT e LONG em colunas individuaizadas
bVendors$Lat = as.numeric(do.call(rbind,strsplit(bVendors$LatLong,","))[,1])
bVendors$Long = as.numeric(do.call(rbind,strsplit(bVendors$LatLong,","))[,2])

cat("\nLatitude: ", head(bVendors$Lat))
cat("\nLongitude: ",head(bVendors$Long))

#Eliminando colunas secundárias
bVendors$location = NULL
bVendors$TownZ = NULL
bVendors$LatLong = NULL


```
